### ISSUE TITLE
influxdb failed: cannot unmarshal number

### ISSUE THREAD

**Issue by lslamp** [unpoller/unpoller#604] opened 2023-09-05 21:30 UTC
I hope that this great product is still supported.

I am not sure what has caused this issue. My grafana dashboards have been working like a dream for multiple years now, but today I did some updates and all of a sudden I have lost all the data within the dashboard, when I look through the logs I see the following.

When I open the dashboard, and do a test on the datasource, the test passes. See below ERROR.

Sep  5 22:55:02 ICANUNIFI unifi-poller[2466]: 2023/09/05 22:55:02 [ERROR] metric fetch for InfluxDB failed: unifi.GetClients(https://127.0.0.1:8443): json: cannot unmarshal number 332967.869306486 into Go struct field Client.data.bytes-r of type int64
Sep  5 22:55:32 ICANUNIFI unifi-poller[2466]: 2023/09/05 22:55:32 [ERROR] metric fetch for InfluxDB failed: unifi.GetClients(https://127.0.0.1:8443): json: cannot unmarshal number 332967.869306486 into Go struct field Client.data.bytes-r of type int64
Sep  5 22:56:02 ICANUNIFI unifi-poller[2466]: 2023/09/05 22:56:02 [ERROR] metric fetch for InfluxDB failed: unifi.GetClients(https://127.0.0.1:8443): json: cannot unmarshal number 1047040.9101312176 into Go struct field Client.data.bytes-r of type int64
Sep  5 22:56:32 ICANUNIFI unifi-poller[2466]: 2023/09/05 22:56:32 [ERROR] metric fetch for InfluxDB failed: unifi.GetClients(https://127.0.0.1:8443): json: cannot unmarshal number 312390.03821562434 into Go struct field Client.data.bytes-r of type int64
Sep  5 22:57:02 ICANUNIFI unifi-poller[2466]: 2023/09/05 22:57:02 [ERROR] metric fetch for InfluxDB failed: unifi.GetClients(https://127.0.0.1:8443): json: cannot unmarshal number 312390.03821562434 into Go struct field Client.data.bytes-r of type int64
Sep  5 22:57:32 ICANUNIFI unifi-poller[2466]: 2023/09/05 22:57:32 [ERROR] metric fetch for InfluxDB failed: unifi.GetClients(https://127.0.0.1:8443): json: cannot unmarshal number 798473.4737403359 into Go struct field Client.data.bytes-r of type int64

![image](https://github.com/unpoller/unpoller/assets/6013759/2c9f6242-38e5-483e-98eb-3ec15e8df3b1)

Do you have any idea why this has happened and how can I fix it?

Thanks
Lawrence

**Comment by platinummonkey** [comment] 2023-09-05 23:58
duplicate of https://github.com/unpoller/unpoller/issues/601

**Closed by platinummonkey** 2023-09-05 23:58 UTC
