### ISSUE TITLE
UnPoller no longer working After Unifi update to 7.5.174

### ISSUE THREAD

**Issue by buchez4281** [unpoller/unpoller#603] opened 2023-09-05 20:02 UTC
Early this morning Unifi network updated to version 7.5.174. Checking my Grafana charts and data stopped coming in immediately after the update.

My Unpoller is running the latest image V2.0.2 in Docker and InfluxDB 1.8.4. I checked the logs for Unpoller and found:
``` 
2023/09/05 19:51:42 [INFO] Re-authenticating to UniFi Controller: https://192.168.1.1
2023/09/05 19:51:42 [ERROR] metric fetch for InfluxDB failed: unifi.GetClients(https://192.168.1.1): json: cannot unmarshal number 1.6566576931041623 into Go struct field Client.data.tx_bytes-r of type int64
```

**Comment by platinummonkey** [comment] 2023-09-05 20:41
duplicate of #601

**Closed by platinummonkey** 2023-09-05 20:41 UTC
