### ISSUE TITLE
List Alarms or List Events will crash the UniFi Controller - Network Application

### ISSUE THREAD

**Issue by aledantas2k12** [unpoller/unpoller#426] opened 2022-09-18 23:31 UTC
UniFi OS UDR 2.5.11

Not sure how to deal with this issue ( It's not unpoller but the awful coding from Ubiquiti)
The following will crash your controller:
https://UDR_IP_ADDRESS/proxy/network/api/s/default/rest/event
https://UDR_IP_ADDRESS/proxy/network/api/s/default/rest/alarm

Everything else is working.

**Comment by bondskin** [comment] 2022-09-19 10:05
Hi, which UNA version are you running on the UDR?

**Comment by aledantas2k12** [comment] 2022-09-19 10:43
UniFi OS (2.5.11) and Network (7.3.69 Early Access) - I also tried with
the Latest Official Firmware and it didn't work.

**Comment by aledantas2k12** [comment] 2022-09-19 10:43
> Hi, which UNA version are you running on the UDR?

UniFi OS (2.5.11) and Network (7.3.69 Early Access) - I also tried with the Latest Official Firmware and it didn't work.

**Comment by platinummonkey** [comment] 2022-12-18 15:09
still having issues with this? I haven't been able to reproduce

**Comment by platinummonkey** [comment] 2022-12-21 03:11
closing as this seems to be a unifi software issue, not an unpoller issue

**Closed by platinummonkey** 2022-12-21 03:11 UTC

**Comment by davidnewhall** [comment] 2022-12-21 03:16
Perhaps we can add a bool to not pull this endpoints? The app probably needs a few more tunable to reduce data into the time series.
