### ISSUE TITLE
Update Synology docs

### ISSUE THREAD

**Issue by PianSom** [unpoller/unpoller#359] opened 2021-06-17 15:57 UTC
User reports - 
following the guide at https://unpoller.com/docs/install/synology to create the influxdb container gets it up and running but it does not create the needed database. I could tell due to the log error noted above. Originally tried to use environment variable INFLUXDB_DB = unifi to create it but it also didn’t work. Managed to do so by first SSH into Synology, and gaining shell access to influx container with “sudo docker exec -it influxdb1 bash” , Then followed ‘Post Setup’ instructions at https://unpoller.com/docs/dependencies/influxdb#post-setup to create the database and user manually.

**Comment by PianSom** [comment] 2021-06-17 19:46
"I can confirm that grafana 8.0.0, 8.0.1 and 8.0.2:latest all have issues downloading plugins in Synology. Currently running 7.5.8 without a hitch, and believe this should be the recommended release in Unifi Poller docs. "

**Comment by davidnewhall** [comment] 2021-06-17 20:23
Appears newer versions of Grafana image aren't installing plugins correctly? Works for me on a dev system I have, but this is what a user got:

> All that said, can’t celebrate yet because now im running into a different issue with grafana and its plugins. I got the container running following the guide, and made sure docker folders had the correct 472 permissions. But needed plugins are not installed properly. Logs show them being downloaded and installed, but grafana can’t use them. Restarting the container as advised doesn’t fix it, neither does running it with high priority. Even tried fixing permissions on the grafana folder and all its content “sudo chown -R 472 -v grafana” but that also didn’t work. Any clues on how to get them installed properly? Feels like im THIS close!!!!
![Screen_Shot_2021-06-17_at_11 48 16_AM](https://user-images.githubusercontent.com/2402929/122467198-1674b980-cf6f-11eb-861d-7d8f1c1dc00c.png)

**Comment by geoff2k** [comment] 2021-11-11 20:05
Just for extra discoverability, posting my database-not-found log output from a partially-successful [synology install](https://unpoller.com/docs/install/synology/):

```
2021-11-11 19:48:50,stdout,2021/11/11 19:48:50 [ERROR] influxdb.Write(points): {"error":"database not found: \"unifi\""}
```

Also, the InfluxDB post-setup steps have moved and can now be found here:

https://unpoller.com/docs/dependencies/influxdb#post-setup

**Comment by davidnewhall** [comment] 2021-11-11 20:10
todo: 
1. add reminder on synology page that influxdb is a dependency and it should be setup first.
1. add "docker" instructions to influxdb setup page.
1. fix broken link(s) on synology page.
1. investigate plugins in Grafana, so far not able to reproduce this. I think this is a plugin signing issue and has since been fixed by Grafana.

**Comment by platinummonkey** [comment] 2022-12-23 04:59
I believe most of this is fixed now 👍

**Closed by platinummonkey** 2022-12-23 04:59 UTC
Labels: docs
