### ISSUE TITLE
Wrong permissions on up.conf

### ISSUE THREAD

**Issue by KOTIJim** [unpoller/unpoller#488] opened 2022-12-23 10:02 UTC
Ubuntu 22.04
Unpoller 2.7.2

When trying to start unpoller as a service the following error message is logged:

`unpoller[1579]: 2022/12/23 09:57:40 [ERROR] finding file: stat /etc/unpoller/up.conf: permission denied`

Starting unpoller with 
`sudo unpoller -c /etc/unpoller/up.conf` 
does work

**Comment by KOTIJim** [comment] 2022-12-23 10:04
I have tried changing the permissions on up.conf to root:root, unpoller:root, unpoller:unpoller unpoller:root but this has no effect

**Comment by platinummonkey** [comment] 2022-12-23 18:17
`v2.7.4` will contain a fix for this. (Currently releasing now)

**Comment by KOTIJim** [comment] 2022-12-23 19:02
Hi

I've purged and installed 2.7.2 and I'm still seeing the same issue with permissions on the up.conf file.
Tested on 2 separate servers, same result

**Comment by platinummonkey** [comment] 2022-12-23 19:08
`2.7.4` is the minimum

**Comment by KOTIJim** [comment] 2022-12-23 19:10
Sorry, I meant 2.7.4 :)

**Comment by KOTIJim** [comment] 2022-12-23 19:34
I also tried removing the unpoller user and group so it would be a "clean" install, still the same issue

**Comment by platinummonkey** [comment] 2022-12-23 22:29
can you ls -al the /etc/unpoller directory? 
as well as id unpoller

**Comment by KOTIJim** [comment] 2022-12-24 08:37
root@dash:~# ll /etc/unpoller/
total 56
drwxr-----   2 root     root      4096 Dec 23 19:17 ./
drwxr-xr-x 111 root     root      4096 Dec 23 19:17 ../
-rw-r--r--   1 unpoller unpoller  5285 Dec 23 18:18 manual.html
-rw-r--r--   1 unpoller unpoller  6339 Dec 23 18:18 readme.html
-rw-r-----   1 unpoller unpoller 10471 Dec 23 19:19 up.conf
-rw-r-----   1 unpoller unpoller 10212 Dec 23 18:17 up.conf.example
-rw-r-----   1 unpoller unpoller  1767 Dec 23 18:17 up.json.example
-rw-r-----   1 unpoller unpoller  1673 Dec 23 18:17 up.yaml.example
root@dash:~# id unpoller
uid=993(unpoller) gid=993(unpoller) groups=993(unpoller)

**Comment by platinummonkey** [comment] 2022-12-24 14:29
That looks correct. But you’re saying systemd is not happy? Maybe try a daemon-reload

**Comment by KOTIJim** [comment] 2022-12-24 14:37
I tried that already and even a complete shutdown and restart. All TNA

**Comment by davidnewhall** [comment] 2022-12-24 19:28
`chmod 0755 /etc/unpoller`

**Comment by platinummonkey** [comment] 2022-12-25 00:01
I’ll try reproducing sometime this week. If the service is running as unpoller the permissions should be correct. 

Not sure I would make other option file mode option +read since it contains a secret to your controller APIs. 

I suspect it something with the user it’s trying to run as.

**Comment by jcornell123** [comment] 2022-12-28 19:41
I'm seeing the same issue on a new fresh install.

root@unpoller:/etc#  ls -al /etc/unpoller/
total 56
drwxr-----   2 root     root      4096 Dec 28 19:36 .
drwxr-xr-x 105 root     root      4096 Dec 28 18:36 ..
-rw-r--r--   1 unpoller unpoller  5285 Dec 23 18:51 manual.html
-rw-r--r--   1 unpoller unpoller  6339 Dec 23 18:51 readme.html
-rw-r-----   1 unpoller unpoller 10211 Dec 28 19:32 up.conf
-rw-r-----   1 unpoller unpoller 10212 Dec 23 18:51 up.conf.example
-rw-r-----   1 unpoller unpoller  1767 Dec 23 18:51 up.json.example
-rw-r-----   1 unpoller unpoller  1673 Dec 23 18:51 up.yaml.example
root@unpoller:/etc# id unpoller
uid=997(unpoller) gid=997(unpoller) groups=997(unpoller)

**Comment by davidnewhall** [comment] 2022-12-28 19:47
> Not sure I would make other option file mode option +read since it contains a secret to your controller APIs.

Thought we were troubleshooting. And +read on the folder doesn't give +read on the file. The quickest fix is still `chmod 0755 /etc/unpoller` but the package needs to ensure this during install. Or it needs to set the group to unpoller and g+r the folder. A future version of this app will probably write its own config file.

**Closed** 2023-01-07 02:13 UTC
